spring:
  redis:
    host: 47.106.144.102
    port: 6379
    password:  #设置连接的服务密码，没有则不需要填写
    database: 0 #设置数据库索引
    timeout: 1000ms #连接超时时间
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 0 # 连接池最小空闲连接
weixin:
  app:
    info:
      volidateToken: dhlpj #这个是验证token
      appid: wx131cd9cc10cc040e
      secret: 67bf65e4732f02ad6a8b56b5fbec57b3
      accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wx131cd9cc10cc040e&secret=67bf65e4732f02ad6a8b56b5fbec57b3
      tokenNameInRedis: access_token #保存在redis中的通信token的key值
    menu:
      urlWithoutAccessToken: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
baidu:
  traslate:
    baseUrl: http://api.fanyi.baidu.com/api/trans/vip/translate
    appid: 20181112000233175
    securityKey: LQqtyUfuS0f6gxuZ96QH